{{/* GENERATED by scripts/build-helm-chart.mjs — do not edit. */}}

{{/* Helm's own labels, beside the ones the manifests already carry. */}}
{{- define "atlas.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end -}}

{{/*
One image reference: {registry}/{repository}:{tag}, registry omitted when empty. A component's
own tag wins; an Atlas image leaves it empty and follows the chart's appVersion, so a release
bumps one number rather than seven.
*/}}
{{- define "atlas.image" -}}
{{- $image := index .ctx.Values.images .name -}}
{{- if not $image -}}{{- fail (printf "no image configured for %s" .name) -}}{{- end -}}
{{- $registry := .ctx.Values.image.registry -}}
{{- $tag := $image.tag | default .ctx.Values.image.tag | default .ctx.Chart.AppVersion -}}
{{- if $registry }}{{ $registry }}/{{ end }}{{ $image.repository }}:{{ $tag }}
{{- end -}}

{{/* The Secret the database credentials come from: the site's, or the one this chart creates. */}}
{{- define "atlas.postgresSecretName" -}}
{{- if .Values.postgres.auth.existingSecret -}}
{{ .Values.postgres.auth.existingSecret }}
{{- else -}}
{{ .Release.Name }}-postgres
{{- end -}}
{{- end -}}

{{/*
Refuse to install without credentials, rather than producing a cluster that half-starts.
Every service reads the database through this Secret; without one, each pod crash-loops on a
missing environment variable and the reason is three kubectl commands away.
*/}}
{{- define "atlas.checkCredentials" -}}
{{- if not .Values.postgres.auth.existingSecret -}}
{{- if or (not .Values.postgres.auth.username) (not .Values.postgres.auth.password) -}}
{{- fail "postgres credentials: set postgres.auth.existingSecret to a Secret you manage, or BOTH postgres.auth.username and postgres.auth.password to have this chart create one" -}}
{{- end -}}
{{- end -}}
{{- end -}}
