// The ffprobe adapter (EP-15.4): the mapping from ffprobe's report to the platform's shape,
// unit-tested on captured reports; then the real binary on a file ffmpeg generates, when the
// tools are on the PATH — in CI they must be (the workflow installs them), on a laptop without
// them that one test skips, like Postgres.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { aspectRatioOf, ffprobeProbe, metadataOf, ProbeRefusal } from '../src/index.ts';

const run = promisify(execFile);

test('the mapping: first format name, the video and audio streams, aspect declared or reduced, rates as numbers', () => {
  const hd = metadataOf({
    format: { format_name: 'mov,mp4,m4a,3gp,3g2,mj2', duration: '12.480000' },
    streams: [
      {
        codec_type: 'video',
        codec_name: 'h264',
        width: 1920,
        height: 1080,
        display_aspect_ratio: '16:9',
        r_frame_rate: '25/1',
        avg_frame_rate: '25/1',
      },
      { codec_type: 'audio', codec_name: 'aac', channels: 2 },
      { codec_type: 'data', codec_name: 'bin_data' },
    ],
  });
  assert.deepEqual(hd, {
    container: 'mov',
    durationSec: 12.48,
    videoCodec: 'h264',
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
    frameRate: 25,
    audioCodec: 'aac',
    audioChannels: 2,
  });

  // Anamorphic SD: the container declares 16:9 over a 720×576 frame — the declaration wins.
  assert.equal(aspectRatioOf({ width: 720, height: 576, display_aspect_ratio: '16:9' }), '16:9');
  // No declaration (ffprobe writes "0:1" or "N/A"): the frame's own reduced ratio.
  assert.equal(aspectRatioOf({ width: 1920, height: 1080, display_aspect_ratio: '0:1' }), '16:9');
  assert.equal(aspectRatioOf({ width: 720, height: 576 }), '5:4');
  assert.equal(aspectRatioOf({ width: 0, height: 0 }), undefined);

  // NTSC: 30000/1001, rounded to what a person writes.
  const ntsc = metadataOf({
    format: { format_name: 'mxf' },
    streams: [
      {
        codec_type: 'video',
        codec_name: 'mpeg2video',
        width: 1920,
        height: 1080,
        avg_frame_rate: '30000/1001',
      },
    ],
  });
  assert.equal(ntsc.frameRate, 29.97);
  assert.equal(ntsc.container, 'mxf');
  assert.equal(ntsc.audioCodec, undefined);

  // Audio only: no picture, no aspect — and that is data, not an error.
  const wav = metadataOf({
    format: { format_name: 'wav', duration: '1.000000' },
    streams: [{ codec_type: 'audio', codec_name: 'pcm_s16le', channels: 1 }],
  });
  assert.deepEqual(wav, {
    container: 'wav',
    durationSec: 1,
    audioCodec: 'pcm_s16le',
    audioChannels: 1,
  });

  // A report with no media stream at all is a refusal, not empty metadata.
  assert.throws(() => metadataOf({ format: { format_name: 'image2' }, streams: [] }), ProbeRefusal);
});

test('the adapter tells the bytes apart from the tool: an exit code is a refusal, a timeout is a refusal, ENOENT is not', async () => {
  const exits = ffprobeProbe({
    run: async () => ({
      stdout: '',
      stderr: '/x: Invalid data found when processing input\n',
      error: Object.assign(new Error('Command failed'), { code: 1, killed: false }),
    }),
  });
  await assert.rejects(exits.probe('/x'), (err: unknown) => {
    assert.ok(err instanceof ProbeRefusal);
    assert.equal(
      err.message,
      '/x: Invalid data found when processing input',
      "ffprobe's own words",
    );
    return true;
  });

  const hangs = ffprobeProbe({
    run: async () => ({
      stdout: '',
      stderr: '',
      error: Object.assign(new Error('Command failed'), { code: null, killed: true }),
    }),
  });
  await assert.rejects(hangs.probe('/x'), (err: unknown) => {
    assert.ok(err instanceof ProbeRefusal);
    assert.match(err.message, /timed out/);
    return true;
  });

  const missing = ffprobeProbe({
    run: async () => ({
      stdout: '',
      stderr: '',
      error: Object.assign(new Error('spawn ffprobe ENOENT'), { code: 'ENOENT' }),
    }),
  });
  await assert.rejects(missing.probe('/x'), (err: unknown) => {
    assert.ok(!(err instanceof ProbeRefusal), 'the tool, not the file');
    return true;
  });
  assert.equal(await missing.available(), false);

  const garbled = ffprobeProbe({ run: async () => ({ stdout: 'not json', stderr: '' }) });
  await assert.rejects(garbled.probe('/x'), /no readable report/);
});

test('the real ffprobe on a real file — generated by ffmpeg; skipped without the tools, never in CI', async (t) => {
  const tools = await run('ffmpeg', ['-version']).then(
    () => true,
    () => false,
  );
  if (!tools) {
    if (process.env['CI'])
      assert.fail('ffmpeg/ffprobe are required in CI: install them in the workflow');
    t.skip('ffmpeg not on the PATH');
    return;
  }
  const dir = await mkdtemp(join(tmpdir(), 'rim-probe-'));
  try {
    // One second of colour bars and a tone, 64×36 (16:9), 25 fps, H.264 + AAC in MP4.
    const clip = join(dir, 'bars.mp4');
    await run('ffmpeg', [
      '-v',
      'error',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=1:size=64x36:rate=25',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=1',
      '-c:v',
      'libx264',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      clip,
    ]);
    const probe = ffprobeProbe();
    assert.equal(await probe.available(), true);
    const meta = await probe.probe(clip);
    assert.equal(meta.container, 'mov');
    assert.equal(meta.videoCodec, 'h264');
    assert.equal(meta.audioCodec, 'aac');
    assert.equal(meta.width, 64);
    assert.equal(meta.height, 36);
    assert.equal(meta.aspectRatio, '16:9');
    assert.equal(meta.frameRate, 25);
    assert.ok(
      meta.durationSec !== undefined && meta.durationSec > 0.9 && meta.durationSec < 1.2,
      `duration ${meta.durationSec}`,
    );

    // Not media: the tool reads it and refuses it — a verdict about the bytes.
    const junk = join(dir, 'junk.mxf');
    await writeFile(junk, Buffer.from('this is not an mxf file, whatever the name says'));
    await assert.rejects(probe.probe(junk), ProbeRefusal);

    // No such binary: the tool, not the file.
    const nowhere = ffprobeProbe({ binary: join(dir, 'no-such-ffprobe') });
    await assert.rejects(nowhere.probe(clip), (err: unknown) => !(err instanceof ProbeRefusal));
    assert.equal(await nowhere.available(), false);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
